version: "3"

services:
 huntly_backend:
  build:
    context: .
  env_file:
    - .env
  ports:
  - "8000:8000" 
  volumes:
    - ./huntly_backend:/huntly_backend
  command: python manage.py runserver 0.0.0.0:8000